name: Run CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Use Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: '22.14.0'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check code style
        run: |
          yarn run fmt
          git --no-pager diff --exit-code

      - name: Build # Type checking
        run: yarn build
